name: doctor
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI Packages
  intl: ^0.20.2
  lottie: ^3.3.1
  logger: ^2.5.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.2.1
  flutter_slidable: ^4.0.0
  flutter_native_splash: ^2.4.6
  flutter_local_notifications: ^19.0.0

  #  Internet Packages
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  internet_connection_checker: ^3.0.1

  # Iconsax
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Cashe Data
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1

  # State Management
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
        - assets/images/
        - assets/icons/
        - assets/logos/
        - assets/animations/
        - assets/lottie/
